name: dart_poo
description:  Modulo da academia do flutter poo
version: 1.0.0
homepage: https://github.com/celycodes/academia_do_flutter

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
